# Generated by Django 4.2.6 on 2023-11-10 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('viaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='viajes.viaje')),
            ],
            options={
                'db_table': 'origen',
            },
        ),
    ]
