# Generated by Django 4.2.6 on 2023-11-09 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viajeros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroAsiento', models.CharField(max_length=45)),
                ('fechaViaje', models.DateField()),
                ('viajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajeros.viajero')),
            ],
        ),
    ]
