# Generated by Django 4.2.6 on 2023-11-15 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='viaje',
            table='viajes',
        ),
    ]
